[workspace]
members = [
    "emulator/core",
    "emulator/frontends/common",
    "emulator/frontends/console",
    "emulator/frontends/minifb",
    "tests/harte_tests"
]
exclude = [
    "emulator/frontends/pixels",
    "emulator/frontends/macroquad",
]
default-members = ["emulator/frontends/minifb"]

[profile.release]
debug = true

