[package]
name = "moa"
version = "0.1.0"
edition = "2018"

[workspace]
members = [".", "frontends/moa-common", "frontends/moa-console", "frontends/moa-minifb", "tests/harte_tests"]
default-members = ["frontends/moa-console"]

[dependencies]
