[package]
name = "moa"
version = "0.1.0"
edition = "2018"

[workspace]
members = [".", "frontends/moa-console"]
default-members = ["frontends/moa-console"]

[features]
default = ["tty"]
tty = ["nix"]

[dependencies]
nix = { version = "0.23", optional = true }

