[workspace]
members = [
    "emulator/core",
    "emulator/frontends/common",
    "emulator/frontends/console",
    "emulator/frontends/minifb",
    "tests/harte_tests"
]
default-members = ["emulator/frontends/minifb"]
