[package]
name = "moa_console"
version = "0.1.0"
edition = "2021"
default-run = "moa-computie"

[dependencies]
log = "0.4"
clap = "3.2.20"
simple_logger = "2.3.0"

moa_core = { path = "../../core" }
moa_common = { path = "../common", features = ["tty"] }

moa_genesis = { path = "../../systems/genesis" }
moa_computie = { path = "../../systems/computie" }
moa_m68k = { path = "../../cpus/m68k" }
moa_peripherals_generic = { path = "../../peripherals/generic" }
moa_peripherals_motorola = { path = "../../peripherals/motorola" }
