[package]
name = "moa_common"
version = "0.1.0"
edition = "2018"

[features]
tty = ["nix"]
audio = ["cpal"]

[dependencies]
moa_core = { path = "../../core" }
nix = { version = "0.23", optional = true }
cpal = { version = "0.13", optional = true }

