[package]
name = "moa_minifb"
version = "0.1.0"
edition = "2018"
default-run = "moa-genesis"

[dependencies]
moa_core = { path = "../../core" }
moa_common = { path = "../common", features = ["audio"] }
minifb = "0.19"
clap = "3.2.20"

moa_genesis = { path = "../../systems/genesis" }
moa_computie = { path = "../../systems/computie" }
moa_trs80 = { path = "../../systems/trs80" }
moa_macintosh = { path = "../../systems/macintosh" }
moa_peripherals_yamaha = { path = "../../peripherals/yamaha" }

