[package]
name = "moa_m68k"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
femtos = { path = "../../libraries/femtos" }
moa_core = { path = "../../core" }
moa_parsing = { path = "../../libraries/parsing" }
